// DO NOT EDIT. generated by github.com/tinywasm/ormc

package agentswitch

import (
	"github.com/tinywasm/model"
	"github.com/tinywasm/orm"
)

type AgentSwitch struct {
	Id string
	IsEnabled bool
	ChangedBy string
	ChangedAt int64
	Reason string
}

func (m *AgentSwitch) ModelName() string { return "agent_switch" }

func (m *AgentSwitch) Schema() []model.Field { return AgentSwitchModel.Fields }

func (m *AgentSwitch) Pointers() []any { return []any{&m.Id, &m.IsEnabled, &m.ChangedBy, &m.ChangedAt, &m.Reason} }

func (m *AgentSwitch) IsNil() bool { return m == nil }

func (m *AgentSwitch) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.Bool("is_enabled", m.IsEnabled)
	w.String("changed_by", m.ChangedBy)
	w.Int("changed_at", m.ChangedAt)
	w.String("reason", m.Reason)
}

func (m *AgentSwitch) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.Bool("is_enabled"); ok { m.IsEnabled = v }
	if v, ok := r.String("changed_by"); ok { m.ChangedBy = v }
	if v, ok := r.Int("changed_at"); ok { m.ChangedAt = v }
	if v, ok := r.String("reason"); ok { m.Reason = v }
}

type AgentSwitchList []*AgentSwitch

func (s *AgentSwitchList) Schema() []model.Field { return nil }
func (s *AgentSwitchList) Pointers() []any     { return nil }
func (s *AgentSwitchList) Len() int             { return len(*s) }
func (s *AgentSwitchList) At(i int) model.Fielder { return (*s)[i] }
func (s *AgentSwitchList) Append() model.Fielder  { v := &AgentSwitch{}; *s = append(*s, v); return v }
func (s *AgentSwitchList) IsNil() bool          { return s == nil }
func (s *AgentSwitchList) EncodeFields(_ model.FieldWriter) {}
func (s *AgentSwitchList) DecodeFields(_ model.FieldReader) {}

func (m *AgentSwitch) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var AgentSwitch_ = struct {
	Id string
	IsEnabled string
	ChangedBy string
	ChangedAt string
	Reason string
}{
	Id: "id",
	IsEnabled: "is_enabled",
	ChangedBy: "changed_by",
	ChangedAt: "changed_at",
	Reason: "reason",
}

func ReadOneAgentSwitch(qb *orm.QB, model *AgentSwitch) (*AgentSwitch, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllAgentSwitch(qb *orm.QB) (AgentSwitchList, error) {
	var results AgentSwitchList
	err := qb.ReadAll(
		func() model.Model { return &AgentSwitch{} },
		func(m model.Model) { results = append(results, m.(*AgentSwitch)) },
	)
	return results, err
}

type StatusEmptyResult struct {
	IsEnabled bool
	ChangedAt int64
}

func (m *StatusEmptyResult) ModelName() string { return "status_empty_result" }

func (m *StatusEmptyResult) Schema() []model.Field { return StatusEmptyResultModel.Fields }

func (m *StatusEmptyResult) Pointers() []any { return []any{&m.IsEnabled, &m.ChangedAt} }

func (m *StatusEmptyResult) IsNil() bool { return m == nil }

func (m *StatusEmptyResult) EncodeFields(w model.FieldWriter) {
	w.Bool("is_enabled", m.IsEnabled)
	w.Int("changed_at", m.ChangedAt)
}

func (m *StatusEmptyResult) DecodeFields(r model.FieldReader) {
	if v, ok := r.Bool("is_enabled"); ok { m.IsEnabled = v }
	if v, ok := r.Int("changed_at"); ok { m.ChangedAt = v }
}

type StatusEmptyResultList []*StatusEmptyResult

func (s *StatusEmptyResultList) Schema() []model.Field { return nil }
func (s *StatusEmptyResultList) Pointers() []any     { return nil }
func (s *StatusEmptyResultList) Len() int             { return len(*s) }
func (s *StatusEmptyResultList) At(i int) model.Fielder { return (*s)[i] }
func (s *StatusEmptyResultList) Append() model.Fielder  { v := &StatusEmptyResult{}; *s = append(*s, v); return v }
func (s *StatusEmptyResultList) IsNil() bool          { return s == nil }
func (s *StatusEmptyResultList) EncodeFields(_ model.FieldWriter) {}
func (s *StatusEmptyResultList) DecodeFields(_ model.FieldReader) {}

func (m *StatusEmptyResult) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type StatusResult struct {
	IsEnabled bool
	ChangedBy string
	ChangedAt int64
	Reason string
}

func (m *StatusResult) ModelName() string { return "status_result" }

func (m *StatusResult) Schema() []model.Field { return StatusResultModel.Fields }

func (m *StatusResult) Pointers() []any { return []any{&m.IsEnabled, &m.ChangedBy, &m.ChangedAt, &m.Reason} }

func (m *StatusResult) IsNil() bool { return m == nil }

func (m *StatusResult) EncodeFields(w model.FieldWriter) {
	w.Bool("is_enabled", m.IsEnabled)
	w.String("changed_by", m.ChangedBy)
	w.Int("changed_at", m.ChangedAt)
	w.String("reason", m.Reason)
}

func (m *StatusResult) DecodeFields(r model.FieldReader) {
	if v, ok := r.Bool("is_enabled"); ok { m.IsEnabled = v }
	if v, ok := r.String("changed_by"); ok { m.ChangedBy = v }
	if v, ok := r.Int("changed_at"); ok { m.ChangedAt = v }
	if v, ok := r.String("reason"); ok { m.Reason = v }
}

type StatusResultList []*StatusResult

func (s *StatusResultList) Schema() []model.Field { return nil }
func (s *StatusResultList) Pointers() []any     { return nil }
func (s *StatusResultList) Len() int             { return len(*s) }
func (s *StatusResultList) At(i int) model.Fielder { return (*s)[i] }
func (s *StatusResultList) Append() model.Fielder  { v := &StatusResult{}; *s = append(*s, v); return v }
func (s *StatusResultList) IsNil() bool          { return s == nil }
func (s *StatusResultList) EncodeFields(_ model.FieldWriter) {}
func (s *StatusResultList) DecodeFields(_ model.FieldReader) {}

func (m *StatusResult) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ToggleArgs struct {
	IsEnabled bool
	ChangedBy string
	Reason string
}

func (m *ToggleArgs) ModelName() string { return "toggle_args" }

func (m *ToggleArgs) Schema() []model.Field { return ToggleArgsModel.Fields }

func (m *ToggleArgs) Pointers() []any { return []any{&m.IsEnabled, &m.ChangedBy, &m.Reason} }

func (m *ToggleArgs) IsNil() bool { return m == nil }

func (m *ToggleArgs) EncodeFields(w model.FieldWriter) {
	w.Bool("is_enabled", m.IsEnabled)
	w.String("changed_by", m.ChangedBy)
	w.String("reason", m.Reason)
}

func (m *ToggleArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.Bool("is_enabled"); ok { m.IsEnabled = v }
	if v, ok := r.String("changed_by"); ok { m.ChangedBy = v }
	if v, ok := r.String("reason"); ok { m.Reason = v }
}

type ToggleArgsList []*ToggleArgs

func (s *ToggleArgsList) Schema() []model.Field { return nil }
func (s *ToggleArgsList) Pointers() []any     { return nil }
func (s *ToggleArgsList) Len() int             { return len(*s) }
func (s *ToggleArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ToggleArgsList) Append() model.Fielder  { v := &ToggleArgs{}; *s = append(*s, v); return v }
func (s *ToggleArgsList) IsNil() bool          { return s == nil }
func (s *ToggleArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ToggleArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ToggleArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ToggleResult struct {
	Ok bool
	IsEnabled bool
}

func (m *ToggleResult) ModelName() string { return "toggle_result" }

func (m *ToggleResult) Schema() []model.Field { return ToggleResultModel.Fields }

func (m *ToggleResult) Pointers() []any { return []any{&m.Ok, &m.IsEnabled} }

func (m *ToggleResult) IsNil() bool { return m == nil }

func (m *ToggleResult) EncodeFields(w model.FieldWriter) {
	w.Bool("ok", m.Ok)
	w.Bool("is_enabled", m.IsEnabled)
}

func (m *ToggleResult) DecodeFields(r model.FieldReader) {
	if v, ok := r.Bool("ok"); ok { m.Ok = v }
	if v, ok := r.Bool("is_enabled"); ok { m.IsEnabled = v }
}

type ToggleResultList []*ToggleResult

func (s *ToggleResultList) Schema() []model.Field { return nil }
func (s *ToggleResultList) Pointers() []any     { return nil }
func (s *ToggleResultList) Len() int             { return len(*s) }
func (s *ToggleResultList) At(i int) model.Fielder { return (*s)[i] }
func (s *ToggleResultList) Append() model.Fielder  { v := &ToggleResult{}; *s = append(*s, v); return v }
func (s *ToggleResultList) IsNil() bool          { return s == nil }
func (s *ToggleResultList) EncodeFields(_ model.FieldWriter) {}
func (s *ToggleResultList) DecodeFields(_ model.FieldReader) {}

func (m *ToggleResult) Validate(action byte) error {
	return model.ValidateFields(action, m)
}
